FROM public.ecr.aws/aws-cli/aws-cli:latest

ARG HELM_VERSION=3.17.3
ARG KUBECTL_VERSION=1.32.0

# helm + kubectl + envsubst + make
RUN yum install -y --allowerasing \
      tar \
      gzip \
      gettext \
      make \
    && yum clean all

# helm
RUN curl -fsSL "https://get.helm.sh/helm-v${HELM_VERSION}-linux-$(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/').tar.gz" \
      | tar -xz --strip-components=1 -C /usr/local/bin \
          "linux-$(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/')/helm"

# kubectl
RUN curl -fsSL "https://dl.k8s.io/release/v${KUBECTL_VERSION}/bin/linux/$(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/')/kubectl" \
      -o /usr/local/bin/kubectl && \
    chmod +x /usr/local/bin/kubectl

WORKDIR /e2e
COPY . .
RUN chmod +x scripts/*.sh

ENTRYPOINT ["make"]
CMD ["help"]
